apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  volumeName: my-pv
  resources:
    requests:
      storage: 500Mi
