apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: echo-server
  name: echo-server
spec:
  containers:
  - command:
    - -text=cenas
    image: hashicorp/http-echo
    name: echo-server
    ports:
    - containerPort: 5678
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
