apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app5
  name: app5
spec:
  containers:
  - image: httpd:2.4
    name: app5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
