apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-volume
        configMap:
          name: nginx-config
      containers:
      - image: nginx:alphine
        name: nginx
        ports:
            - containerPort: 80
        imagePullPolicy: IfNotPresent
        volumeMounts:
            - name: nginx-volume
              mountPath: /usr/share/nginx/html
              readOnly: true
        resources: {}
status: {}